name: Delete all APIs
on:
  workflow_dispatch:

jobs:
  apim:
    strategy:
      matrix:
        api:
          - CFT
          - FM
          - ST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2
      - name: Delete from APIM
        uses: Axway/presales-apim-cli-action@v0
        env:
          APIM_USER: ${{ secrets.APIM_USER }}
          APIM_PASS: ${{ secrets.APIM_PASS }}
          APIM_HOST: ${{ secrets.APIM_HOST }}
          APIM_PORT: ${{ secrets.APIM_PORT }}
        with:
          command: api delete -c apis/${{ matrix.api }}/api-config.json